# Generated by Django 4.1 on 2022-08-21 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('trade_date', models.DateField(auto_now_add=True)),
                ('trade_time', models.TimeField(auto_now_add=True)),
                ('trade_amount', models.PositiveIntegerField(default=0)),
                ('trade_type', models.CharField(choices=[('BY', 'BUY'), ('SL', 'SELL')], max_length=5)),
                ('profit_loss', models.IntegerField(blank=True)),
                ('trade_status', models.CharField(choices=[('ACT', 'ACTIVE'), ('IN-ACT', 'INACTIVE')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
