# Generated by Django 3.2.6 on 2022-08-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='order_id',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
