# Generated by Django 4.1 on 2022-08-24 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_trades_trade_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='trade_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)]),
        ),
    ]
