# Generated by Django 4.1 on 2022-08-26 00:06

import deposits.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_name', models.CharField(max_length=50)),
                ('deposit_address', models.CharField(max_length=255)),
                ('deposit_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('deposit_upload', models.FileField(blank=True, null=True, upload_to=deposits.models.get_deposit_upload_path)),
            ],
            options={
                'verbose_name_plural': 'Deposit Method',
            },
        ),
        migrations.CreateModel(
            name='UserDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_deposit_amount', models.PositiveSmallIntegerField()),
                ('user_deposit_upload', models.FileField(null=True, upload_to=deposits.models.get_deposit_upload_path)),
                ('user_deposit_status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=100)),
                ('user_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_deposit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='deposits.depositmethod')),
            ],
            options={
                'verbose_name_plural': 'User Deposits',
            },
        ),
    ]
