# Generated by Django 4.1 on 2022-08-26 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Add new withdrawal',
                'verbose_name_plural': 'Add new withdrawal',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_address', models.CharField(max_length=255)),
                ('w_amount', models.PositiveIntegerField()),
                ('w_status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=100)),
                ('w_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_withdrawal_type', to='withdrawal.withdrawaltype')),
                ('w_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_withdrawal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Add Withdrawl Method',
            },
        ),
    ]
