# Generated by Django 3.2.6 on 2022-08-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawaltype',
            options={'verbose_name_plural': 'Add Widthrawal Type'},
        ),
    ]
